type: mysql
file_name: output
filter: title == 'BIG DATA AND DATA QUALITY'
query: sort_order=asc&sort_field=article_number&publication_title=python

#filter: title == 'Hydrothermal scheduling'
#filter: title == 'CZAS KULTURY'
#filter: title == 'Advanced Applications'


# Example of filter
# title == 'CA-A CANCER JOURNAL FOR CLINICIANS'
# title == 'MMWR RECOMMENDATIONS AND REPORTS'
# title == 'NEW ENGLAND JOURNAL OF MEDICINE'
# year == '2017'
# year == '2017'
# scimago_value > 1.0
# scimago_value > 20.0


#Mergulhar até o nome do autor
#Mergulhar até o keywords

#query: sort_order=asc&sort_field=article_number&article_title=bigdata
