type: mysql
file_name: output
filter: title == 'CONIC OPTIMIZATION'

#filter: year == '2022'

# Example of filter
# title == 'CA-A CANCER JOURNAL FOR CLINICIANS'
# title == 'MMWR RECOMMENDATIONS AND REPORTS'
# title == 'NEW ENGLAND JOURNAL OF MEDICINE'
# year == '2017'
# year == '2017'
# scimago_value > 1.0
# scimago_value > 20.0

query: sort_order=asc&sort_field=article_number&publication_title=python


